name:    test-package
version: '0.1.0.0'

internal-libraries:
  test-package-internal:
    source-dirs: internal-lib
    dependencies:
    - base

library:
  source-dirs: lib
  dependencies:
  - base
  - test-package-internal

executables:
  test-package-exe:
    main: Main.hs
    source-dirs: exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - gitrev
    - test-package
    - test-package-internal
